import { InvestmentPlan } from '../types/crypto';

export const OFFICIAL_INVESTMENT_PLANS: InvestmentPlan[] = [
  {
    id: 'plan_starter',
    tier: 1,
    name: 'Starter Plan',
    depositAmount: 5,
    totalPayout: 9,
    totalDifference: 4,
    dailyClaim: 0.22,
    durationDays: 40,
    tagline: 'Ideal for trial node staking and low barrier entry.',
  },
  {
    id: 'plan_basic',
    tier: 2,
    name: 'Basic Plan',
    depositAmount: 10,
    totalPayout: 18,
    totalDifference: 8,
    dailyClaim: 0.45,
    durationDays: 40,
    tagline: 'Standard tier with consistent 40-day contract settlement.',
  },
  {
    id: 'plan_standard',
    tier: 3,
    name: 'Standard Plan',
    depositAmount: 15,
    totalPayout: 27,
    totalDifference: 12,
    dailyClaim: 0.67,
    durationDays: 40,
    tagline: 'Balanced yield pool with boosted automated claiming.',
    popular: true,
  },
  {
    id: 'plan_silver',
    tier: 4,
    name: 'Silver Plan',
    depositAmount: 20,
    totalPayout: 36,
    totalDifference: 16,
    dailyClaim: 0.90,
    durationDays: 40,
    tagline: 'Enhanced capacity allocation with daily yield payout.',
  },
  {
    id: 'plan_gold',
    tier: 5,
    name: 'Gold Plan',
    depositAmount: 50,
    totalPayout: 120,
    totalDifference: 70,
    dailyClaim: 3.00,
    durationDays: 40,
    tagline: 'High-throughput staking with +140% proposed net margin.',
    popular: true,
  },
  {
    id: 'plan_premium',
    tier: 6,
    name: 'Premium Plan',
    depositAmount: 100,
    totalPayout: 250,
    totalDifference: 150,
    dailyClaim: 6.30,
    durationDays: 40,
    tagline: 'Institutional priority pool with maximized daily allocation.',
  },
];
